swagger: '2.0'
info: 
  title: PIR Calculator
  version: ""
host: test1.services.ird.govt.nz
basePath: /gateway/calculators/
schemes: 
  - https
paths: 
  /pir: 
    post: 
      tags: 
        - 'Prescribed Investor Rate (PIR) Calculator - Post'
      summary: 'Prescribed Investor Rate (PIR) Calculator - Post'
      description: This API is called to request a “suggested” PIR (Prescribed Investor Rate) value for a customer. The target consumers of this API are the PIE (Portfolio Investment Entity) providers.
      operationId: pirPOST
      consumes: 
        - 'application/json; charset=utf-8'
      produces: 
        - 'application/json; charset=utf-8'
      parameters: 
        - name: body
          in: body
          required: true
          schema: 
            $ref: '#/definitions/pir_POST_Request'
      responses: 
        '200': 
          description: 'HttpStatus: 200 - OK'
          schema: 
            $ref: '#/definitions/pir_POST_Response200'
        '400': 
          description: 'HttpStatus: 400 - BadRequest'
          schema: 
            $ref: '#/definitions/pir_POST_Response400'
        '401': 
          description: 'HttpStatus: 401 - Unauthorized'
          schema: 
            $ref: '#/definitions/pir_POST_Response401'
        '500': 
          description: 'HttpStatus: 500 - InternalServerError'
          schema: 
            $ref: '#/definitions/pir_POST_Response500'
        default: 
          description: ' '
          schema: 
            $ref: '#/definitions/pir_POST_ResponseDefault'
definitions: 
  pir_POST_Request: 
    type: object
    required: 
      - IRD
      - PieIRD
    properties: 
      IRD: 
        type: string
        description: '<p>Investor IRD number. This field is validated
to ensure that it exists and is active. The
calculated suggested PIR value will be this
investor’s current PIR. The IRD field will be
the PIE investor or KiwiSaver Scheme
member. Must comply with Modulus 11 check. If IR number is 8 characters, then
pad with leading zero ''0'' to make a
total of 9 characters.
Numeric only, any letters or special
characters will cause the check digit
validation to fail.</p>'
        maxLength: 9
        minLength: 9
      PieIRD: 
        type: string
        description: '<p>PIE IRD number. This field is validated to
ensure that it exists, is active and is a PIE
entity. The PIE IRD will be either a PIE
financial institution or Kiwisaver Schema
provider. Must comply with Modulus 11 check. If IR number is 8 characters, then
pad with leading zero ''0'' to make a
total of 9 characters</p>'
        maxLength: 9
        minLength: 9
      FormattedName: 
        type: string
        description: '<p>Formatted name of the investor</p>'
        maxLength: 255
      Name: 
        type: object
        required: 
          - FirstName
          - LastName
        properties: 
          FirstName: 
            type: string
            description: '<p>First name of the investor</p>'
            maxLength: 255
            minLength: 1
          MiddleName: 
            type: string
            description: '<p>Middle name of the investor</p>'
            maxLength: 255
          LastName: 
            type: string
            description: '<p>Last name of the investor</p>'
            maxLength: 255
            minLength: 1
      Dob: 
        type: string
        description: '<p>Date of birth of the investor</p>'
      FormattedAddress: 
        type: string
        description: '<p>Investor formatted address</p>'
        maxLength: 255
      Address: 
        type: object
        required: 
          - Street
          - City
          - Country
        properties: 
          Street: 
            type: string
            description: '<p>Investor street</p>'
            maxLength: 60
            minLength: 1
          City: 
            type: string
            description: '<p>Investor city</p>'
            maxLength: 50
            minLength: 1
          PostCode: 
            type: string
            description: '<p>Investor Post Code</p>'
            maxLength: 10
          State: 
            type: string
            description: '<p>Investor State</p>'
            maxLength: 30
          Country: 
            type: string
            description: '<p>Country of the address</p>'
            maxLength: 2
            minLength: 1
  pir_POST_Response200: 
    type: object
    required: 
      - IRD
      - PieIRD
      - SuggestedPirRate
      - Default
    properties: 
      IRD: 
        type: string
        description: '<p>Investor IRD number. This field is validated
to ensure that it exists and is active. The
calculated suggested PIR value will be this
investor’s current PIR. The IRD field will be
the PIE investor or KiwiSaver Scheme
member. Must comply with Modulus 11 check. If IR number is 8 characters, then
pad with leading zero ''0'' to make a
total of 9 characters.
Numeric only, any letters or special
characters will cause the check digit
validation to fail.</p>'
      PieIRD: 
        type: string
        description: '<p>PIE IRD number. This field is validated to
ensure that it exists, is active and is a PIE
entity. The PIE IRD will be either a PIE
financial institution or Kiwisaver Schema
provider. Must comply with Modulus 11 check. If IR number is 8 characters, then
pad with leading zero ''0'' to make a
total of 9 characters</p>'
      SuggestedPirRate: 
        type: number
        description: '<p>PIR for the investor</p>'
      Default: 
        type: boolean
        description: '<p>Default PIR</p>'
  pir_POST_Response400: 
    type: object
    required: 
      - errors
    properties: 
      errors: 
        type: array
        description: Validation array
        items: 
          type: object
          description: Errors Object
          required: 
            - code
            - type
            - message
          properties: 
            code: 
              type: string
              description: 'Error code For validation, Security, Or server type responses.<br><br><table><tbody><tr><th>code</th><th>description</th></tr><tr><td>PIR110</td><td>Missing/invalid required content parameter.</td></tr><tr><td>PIR120</td><td>Invalid optional content parameters.</td></tr><tr><td>PIR130</td><td>Failed validation. Expecting 9 digit valid IRD number.</td></tr><tr><td>PIR140</td><td>Not found in system.</td></tr></tbody></table>'
              maxLength: 6
              enum: 
                - PIR110
                - PIR120
                - PIR130
                - PIR140
            type: 
              type: string
              description: Type of validation code returned
              enum: 
                - result
                - security
                - server
                - validation
            message: 
              type: string
              description: Error Message
  pir_POST_Response401: 
    type: object
    required: 
      - errors
    properties: 
      errors: 
        type: array
        description: Validation array
        items: 
          type: object
          description: Errors Object
          required: 
            - code
            - type
            - message
          properties: 
            code: 
              type: string
              description: 'Error code For validation, Security, Or server type responses.<br><br><table><tbody><tr><th>code</th><th>description</th></tr><tr><td>EV1000</td><td>No incoming POST content found</td></tr><tr><td>EV1023</td><td>No customer associated to TLS cert</td></tr><tr><td>EV1024</td><td>Authentication error</td></tr><tr><td>EV1025</td><td>Missing OAuth or JWT token in the HTTP header</td></tr><tr><td>EV1026</td><td>Authentication error, Issued date or expiry date is invalid</td></tr><tr><td>EV1027</td><td>Certificate or credential could not be found</td></tr><tr><td>EV1028</td><td>Authentication error, JWT signature validation failed</td></tr><tr><td>EV1029</td><td>Authentication error, JWT algorithm not configured on credential doc</td></tr><tr><td>EV1030</td><td>Unknown authentication error</td></tr><tr><td>EV1040</td><td>Start logon associated to OAuth token does not have access to any accounts or customers</td></tr><tr><td>EV1041</td><td>Start logon associated to OAuth token does not have access to member/investor customer</td></tr><tr><td>EV1042</td><td>Unable to validate API consumer to JWT provided</td></tr><tr><td>EV1043</td><td>Unable to validate JWT to member/investor IRD number provided</td></tr></tbody></table>'
              maxLength: 6
              enum: 
                - EV1000
                - EV1023
                - EV1024
                - EV1025
                - EV1026
                - EV1027
                - EV1028
                - EV1029
                - EV1030
                - EV1040
                - EV1041
                - EV1042
                - EV1043
            type: 
              type: string
              description: Type of validation code returned
              enum: 
                - result
                - security
                - server
                - validation
            message: 
              type: string
              description: Error Message
  pir_POST_Response500: 
    type: object
    required: 
      - errors
    properties: 
      errors: 
        type: array
        description: Validation array
        items: 
          type: object
          description: Errors Object
          required: 
            - code
            - type
            - message
          properties: 
            code: 
              type: string
              description: 'Error code For validation, Security, Or server type responses.<br><br><table><tbody><tr><th>code</th><th>description</th></tr><tr><td>PIR150</td><td>Unknown error occurred while processing.</td></tr></tbody></table>'
              maxLength: 6
              enum: 
                - PIR150
            type: 
              type: string
              description: Type of validation code returned
              enum: 
                - result
                - security
                - server
                - validation
            message: 
              type: string
              description: Error Message
  pir_POST_ResponseDefault: 
    type: object
    required: 
      - errors
    properties: 
      errors: 
        type: array
        description: Validation array
        items: 
          type: object
          description: Errors Object
          required: 
            - code
            - type
            - message
          properties: 
            code: 
              type: string
              description: 'Error code For validation, Security, Or server type responses.<br><br><table><tbody><tr><th>code</th><th>description</th></tr><tr><td>PIR110</td><td>Missing/invalid required content parameter.</td></tr><tr><td>PIR120</td><td>Invalid optional content parameters.</td></tr><tr><td>PIR130</td><td>Failed validation. Expecting 9 digit valid IRD number.</td></tr><tr><td>PIR140</td><td>Not found in system.</td></tr></tbody></table>'
              maxLength: 6
              enum: 
                - PIR110
                - PIR120
                - PIR130
                - PIR140
            type: 
              type: string
              description: Type of validation code returned
              enum: 
                - result
                - security
                - server
                - validation
            message: 
              type: string
              description: Error Message